### ISSUE TITLE
Error installing mobsim

### ISSUE THREAD

**Issue by rueuntal** [MoBiodiv/mobsim#11]
Hi Felix - I tried to install `mobsim` but encountered the following error: 
```
Error: processing vignette 'Biodiversity_Changes.Rmd' failed with diagnostics:
there is no package called 'GUILDS'
```
When I turned off `build_vignettes`, it worked fine.

**Comment by FelixMay** [comment]
Hi @rueuntal, 
In the vignette I use the package `untb`. I read that there is a bug in `devtools`, which does not properly install the dependencies os the dependencies of `mobsim`. So it should work after you manually installed the packages needed by `untb`. However, as untb is not really important I rather plan to remove this dependency from `mobsim`.

Thanks for the hint!

**Comment by FelixMay** [comment]
Hi @rueuntal, I removed the dependency of `mobsim` on `untb` know. Please try again. As I mentioned, because of the `devtools` bug, you might nee to install the dependencies of `vegan`, `sads`, and `Rcpp` manually.

**Comment by rueuntal** [comment]
Hi @FelixMay - thanks, it is working now. Yesterday when I tried to manually install `GUILDS` it kept saying connection not detected, but now I'm able to install `mobsim` after installing `GUILDS` and a few other packages.
