### ISSUE TITLE
need to run spell check on package

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobsim#14]
I just pushed a very minor commit 46bdd88278bbe41777a3df2e2a5032bc4bfde60f that removed a special character so that the function `spelling::spell_check_package()` would run. This package can be found here: https://github.com/ropensci/spelling/
There does appear to be some spelling errors.

**Comment by FelixMay** [comment]
Hi @dmcglinn , thanks for this hint. As far as I remember during the CRAN pre-submission checks there was a spell check on the function documentation but not on the vignettes for instance. So I will include that!
