### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobsim#20]
Hey @FelixMay I just added continuous integration on the `mobr` repo it was pretty easy. If you'd like I can set this up for this repo as well. See the `.travis.yml` file: https://github.com/MoBiodiv/mobr/blob/master/.travis.yml
and linked tag on `README.md`: https://github.com/MoBiodiv/mobr/blob/master/README.md

**Comment by FelixMay** [comment]
Hi @dmcglinn, could you give me some hints or a link with explanations what the continuous integration does and why it is useful?

**Comment by dmcglinn** [comment]
so basically it runs `devtools::check` and reports if there are any errors every time you merge changes to master. This is useful because it is a bit of a pain to do this on your local machine and you can get an email telling you if the merge caused the check to fail and why.
