### ISSUE TITLE
preparing for publication 

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobsim#21]
Hey @FelixMay it is probably a good idea to create a software release in github once the manuscript is accepted so there is a clear time-stamped version of the repo showing the version of the code at time of publication. This is easy to do just click `releases` at the project home page and create a new one.

**Comment by FelixMay** [comment]
Hi @dmcglinn, thanks for the hint. mobsim is already on CRAN. Do you think the github release is still important in this case? Well, I guess it is still useful?

**Comment by dmcglinn** [comment]
It seems like the version at publication may be slightly updated related to the CRAN submission. In general they ask on CRAN that you only push major updates because of the human aspect involved in processing the package checks. In general providing release versions through CRAN and github is a useful practice I think. Better to make the historical code modular and easy to access.
