### ISSUE TITLE
example for sim_poisson_community does not work

### ISSUE THREAD

**Issue by KatharinaGerstner** [MoBiodiv/mobsim#8]
In the example the code is sim_poisson_community(S = 20, N = 500, cv = 1) but since variable names changed it should be sim_poisson_community(s_pool = 20, n_sim = 500, cv_abund = 1)

**Comment by FelixMay** [comment]
Hallo Katharina,
ich habe in den letzten Tage an der Dokumentation der Funktionen gearbeitet und den Fehler (lokal) vermutlich schon behoben. Ich bin aber noch nicht ganz fertig und würde dann erst den push machen, wenn ich damit ganz durch bin. Ich sage dir dann Bescheid! Jetzt brauchst du noch nicht den Code checken. Dann lieber das Manuskript!

**Comment by FelixMay** [comment]
Ups, ich nehme meinen letzten Kommentar zurück. Der Fehler war noch drin! DANKE!
